name: sazones_semanales
description: "Esta aplicación está diseñada para gestionar eficientemente el inventario de la alacena personal, permitiendo actualizar las existencias de productos después de cada compra en el supermercado. La aplicación se enfoca en facilitar el registro y seguimiento de productos para una persona que vive sola, con gustos y restricciones alimentarias bien definidos."

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

assets:
  - lib/src/sql/postgres_config/.env.development
  - lib/src/sql/postgres_config/.env.production
  - lib/src/api/unsplash/.env.development
  - lib/src/api/unsplash/.env.production

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.5.4

dependencies:
  flutter:
    sdk: flutter
  postgres: ^3.4.8
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  http: ^1.3.0
  # Inventory management dependencies
  sqflite: ^2.3.0
  provider: ^6.1.1
  camera: ^0.10.5+5
  speech_to_text: ^6.5.1
  flutter_local_notifications: ^19.0.0
  # Additional utility dependencies
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  permission_handler_android: ^13.0.1
  equatable: ^2.0.7
  sqflite_common_ffi: ^2.3.6
  mobile_scanner: ^5.2.3
  timezone: ^0.10.1
  uuid: ^4.5.1
  intl: ^0.19.0
  image_picker: ^0.8.9
  camera_windows: ^0.2.1
  camera_platform_interface: ^2.5.2
  file_picker: ^5.3.1 # Para seleccionar archivos en Windows
  google_fonts: ^6.1.0 # Para usar fuentes de Google

flutter:
  uses-material-design: true