name: sazones_semanales
description: "Marketplace Startup offering On-Demand Private Chefs dedicated to weekly Meal Prep services."

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

assets:
  - lib/src/sql/postgres_config/.env.development
  - lib/src/sql/postgres_config/.env.production
  - lib/src/api/unsplash/.env.development
  - lib/src/api/unsplash/.env.production

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependencies:
  flutter:
    sdk: flutter
  postgres: ^3.4.8
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  http: ^1.3.0
  # Inventory management dependencies
  sqflite: ^2.3.0
  provider: ^6.1.1
  camera: ^0.10.5+5
  speech_to_text: ^6.5.1
  flutter_local_notifications: ^19.0.0
  # Additional utility dependencies
  path: ^1.9.0
  permission_handler: ^12.0.1
  permission_handler_android: ^13.0.1
  equatable: ^2.0.5
  sqflite_common_ffi: ^2.3.6
  mobile_scanner: ^5.2.3

flutter:
  uses-material-design: true