name: sazones_semanales
description: "Marketplace Startup offering On-Demand Private Chefs dedicated to weekly Meal Prep services."

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

assets:
  - lib/src/sql/postgres_config/.env.development
  - lib/src/sql/postgres_config/.env.production
  - lib/src/api/unsplash/.env.development
  - lib/src/api/unsplash/.env.production

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependencies:
  flutter:
    sdk: flutter
  postgres: ^3.4.8
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  http: ^1.3.0

flutter:
  uses-material-design: true